---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  vars:
    keypair: cap2020
    instance_type: t2.micro
    security_group: sg-02728b7364aa7627c
    volume_size: 10
    region: us-west-2
    ec2_access_key: "{{ lookup('env', 'ANSIBLE_KEY') }}"
    ec2_secret_key: "{{ lookup('env', 'ANSIBLE_VAL') }}"
  roles:
    - role: bujjibhuvan.intellipaat
      tags: molecule-idempotence-notest
